language: node_js
node_js:
  - 10.16.3
services:
  - elasticsearch
install:
  - npm install
before_script:
  - sleep 100
  - sudo service elasticsearch start
  - curl -v http://localhost:9200/
  - node discovery.js
  - sleep 10
