sudo: required
language: node_js
node_js:
- 10.16.3
env:
  global:
  - CXX=g++-4.8
  - CHROME_BIN=/usr/bin/google-chrome
  - DISPLAY=:99.0
  - ELASTICSEARCH_URL=http://localhost:9200
services:
- elasticsearch
addons:
  chrome: stable
before_install:
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
  -in .env.enc -out .env -d
install:
- npm install
- sudo apt update
- sudo apt install openjdk-8-jdk
before_script:
- sudo service elasticsearch start
- sleep 50
- curl -PUT ELASTICSEARCH_URL'/test_index' -d
#- curl -v http://localhost:9200/
script:
- node discovery.js &
- sleep 10
#- curl http://localhost:9007/search
- npm test
