sudo: required
language: node_js
node_js:
  - 10.16.3
env:
  global:
    - CXX=g++-4.8
    - CHROME_BIN=/usr/bin/google-chrome
    - DISPLAY=:99.0
services:
  - elasticsearch
addons:
  chrome: stable
before_install:
  - openssl aes-256-cbc -K $encrypted_355e94ba1091_key -iv $encrypted_355e94ba1091_iv -in super_secret.txt.enc -out super_secret.txt -d
install:
  - npm install
before_script:
  - sleep 50
  - sudo service elasticsearch start
  - curl -v http://localhost:9200/
script:
  - sudo apt update
  - sudo apt install openjdk-8-jdk
  - 'java --version'
  - node discovery.js &
  - sleep 10
  - curl http://localhost:9007/search
  - npm test
